version: '3'
services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start file:/mydata/mydatabase.db
    ports:
      - "8000:8000"
    volumes:
      - mydata:/mydata
    user: "root"

volumes:
  mydata: