version: '3'
services:
  db:
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
      POSTGRES_DB: database
    volumes:
      - mydata:/var/lib/postgresql/data

volumes:
  mydata: