services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data

  mockoidc:
    image: ghcr.io/navikt/mock-oauth2-server:2.1.5
    ports:
      - 8080:8080
    environment:
      JSON_CONFIG: >
        {
          "interactiveLogin": true,
          "httpServer": "NettyWrapper",
          "tokenCallbacks": [
            {
              "issuerId": "chase",
              "tokenExpiry": 120,
              "requestMappings": [
                {
                  "requestParam": "scope",
                  "match": "scope1",
                  "claims": {
                    "sub": "subByScope",
                    "aud": [
                      "audByScope"
                    ]
                  }
                }
              ]
            }
          ]
        }