name: Build
on: [pull_request]

# TODO run tests too
jobs:
  chase-build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install all dependencies
        run: bun i

        # typecheck the backend since it is required for the frontend
      - name: Typecheck backend
        working-directory: ./chase/backend
        run: bun run typecheck

      - name: Run build
        run: bun run build
        working-directory: ./chase/frontend

  chase-build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1

      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-${{ matrix.bun }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.bun }}-bun-

      - name: Install all dependencies
        run: bun i

      - name: Typecheck
        working-directory: ./chase/backend
        run: bun run typecheck

      - name: Run build
        working-directory: ./chase/backend
        run: bun run build
