import { LanguageProvider } from "@inlang/paraglide-next";
import { languageTag } from "@/paraglide/runtime.js";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import "./globals.css";
import "@/styles/theme_light.scss";
import "@/styles/fontawesome/css/all.css";
import Footer from "./Footer";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<PrimeReactProvider>
			<LanguageProvider>
				<html lang={languageTag()}>
					<body
						className={`${geistSans.variable} ${geistMono.variable} antialiased`}
					>
						{children}
						<Footer />
					</body>
				</html>
			</LanguageProvider>
		</PrimeReactProvider>
	);
}
