import { LanguageProvider } from "@inlang/paraglide-next";
import { languageTag } from "@/paraglide/runtime.js";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { PrimeReactProvider } from "primereact/api";
import Head from "next/head";
import "./globals.css";
import "@/themes/theme_light.scss";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<PrimeReactProvider>
			<LanguageProvider>
				<html lang={languageTag()}>
					<Head>
						<link
							href="/fontawesome/css/fontawesome.css"
							rel="stylesheet"
						/>
						<link
							href="/fontawesome/css/brands.css"
							rel="stylesheet"
						/>
						<link
							href="/fontawesome/css/solid.css"
							rel="stylesheet"
						/>
						<link
							href="/fontawesome/css/sharp-thin.css"
							rel="stylesheet"
						/>
						<link
							href="/fontawesome/css/duotone-thin.css"
							rel="stylesheet"
						/>
						<link
							href="/fontawesome/css/sharp-duotone-thin.css"
							rel="stylesheet"
						/>
					</Head>

					<body
						className={`${geistSans.variable} ${geistMono.variable} antialiased`}
					>
						{children}
					</body>
				</html>
			</LanguageProvider>
		</PrimeReactProvider>
	);
}
