version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the host network, so that every port is already available from the host.
    network_mode: "host"

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    network_mode: "host"
      
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes: 
      - redis-data:/data
    network_mode: "host"

  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '3777:80'
      - '5968:25'
    volumes:
      - smtp4dev:/smtp4dev
    environment:
      - RelayOptions__Login=dev
      - RelayOptions__Password=dev

volumes:
  postgres-data:
  redis-data:
  smtp4dev: