services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '3777:80'
      - '5968:25'
    environment:
      - RelayOptions__Login=dev
      - RelayOptions__Password=dev

  authentik-postgresql:
    image: docker.io/library/postgres:12-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./docker/authentik-postgres:/var/lib/postgresql/data
  authentik-redis:
    image: redis
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - ./docker/authentik-redis:/data
  authentik-server:
    image: ghcr.io/goauthentik/server
    command: server
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: postgres
      AUTHENTIK_POSTGRESQL__PASSWORD: postgres
      AUTHENTIK_DISABLE_STARTUP_ANALYTICS: true
      AUTHENTIK_ERROR_REPORTING__ENABLED: false
      PG_PASS: postgres
      AUTHENTIK_SECRET_KEY: GXXVexf9DcDk8CPfYbfK7y8AavtSLwopFbAuusTAGkQrro
    ports:
      - 9000:9000
      - 9443:9443
    depends_on:
      - authentik-postgresql
      - authentik-redis
    volumes:
      - ./docker/authentik-media:/media
      - ./docker/authentik-custom-templates:/templates
  authentik-worker:
    image: ghcr.io/goauthentik/server
    command: worker
    environment:
      AUTHENTIK_REDIS__HOST: authentik-redis
      AUTHENTIK_POSTGRESQL__HOST: authentik-postgresql
      AUTHENTIK_POSTGRESQL__USER: postgres
      AUTHENTIK_POSTGRESQL__NAME: postgres
      AUTHENTIK_POSTGRESQL__PASSWORD: postgres
      PG_PASS: postgres
      AUTHENTIK_SECRET_KEY: GXXVexf9DcDk8CPfYbfK7y8AavtSLwopFbAuusTAGkQrro
      AUTHENTIK_EMAIL__HOST: smtp4dev
      AUTHENTIK_EMAIL__PORT: 25
      AUTHENTIK_EMAIL__USERNAME: dev
      AUTHENTIK_EMAIL__PASSWORD: dev
      AUTHENTIK_EMAIL__USE_TLS: false
      AUTHENTIK_EMAIL__USE_SSL: false
      AUTHENTIK_EMAIL__TIMEOUT: 10
      AUTHENTIK_EMAIL__FROM: authentik@localhost
      AUTHENTIK_BOOTSTRAP_PASSWORD: admin
      AUTHENTIK_BOOTSTRAP_TOKEN: admin
      AUTHENTIK_BOOTSTRAP_EMAIL: admin@admin.de
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/authentik-media:/media
      - ./docker/authentik-certs:/certs
      - ./docker/authentik-custom-templates:/templates
    depends_on:
      - authentik-postgresql
      - authentik-redis