services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  redis:
    image: redis
    ports:
      - '6379:6379'
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '3777:80'
      - '5968:25'
    environment:
      - RelayOptions__Login=dev
      - RelayOptions__Password=dev