# TODO document docker requirement for setup

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes: 
      - ./.redis-data:/data
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '3777:80'
      - '5968:25'
    volumes:
      - ./.smtp4dev:/smtp4dev
    environment:
      - RelayOptions__Login=dev
      - RelayOptions__Password=dev