name: Build
on: [pull_request]

# TODO run tests too
jobs:
  chase-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}
      - name: Run build
        run: npm run build
  chase-build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install all dependencies
        run: npm run install-all

      - name: Run build
        working-directory: ./chase/backend
        run: npm run build
        
      - name: Run the server
        id: run
        env:
          CI: "true"
        run:  | 
          timeout 20s node ./build/main.js || true