name: Build
on: [pull_request]

# TODO run tests too
jobs:
  chase-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
  chase-build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Run the server
        run: |
          timeout 20s node ./build/main.js
          exit_code=$? # Get the exit code of the previous command

          if [ $exit_code -eq 124 ]; then
            echo "Server started without errors"
            exit 0
          elif [ $exit_code -ne 0 ]; then
            echo "Server encountered an error"
            exit 1
          else
            echo "Server exited unexpectedly"
            exit 1
          fi