name: Build
on: [pull_request]

# TODO run tests too
# TODO bring the frontend to bun when its ready
jobs:
  chase-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun i

      - name: Run build
        run: bun run build
  chase-build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1

      - name: Install all dependencies
        run: bun run install-all

      - name: Generate prisma types
        working-directory: ./chase/backend
        run: bunx prisma generate

      - name: Run build
        working-directory: ./chase/backend
        run: bun run build
        
        # test if the server starts without errors
      - name: Run the server
        id: run
        env:
          CI: "true"
        run:  | 
          timeout 20s bun run ./build/main.js || true