name: Build
on: [pull_request]

# TODO run tests too
jobs:
  chase-build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
  chase-build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./chase/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build
        
      - name: Run the server
        id: run
        env:
          CI: "true"
        run:  | 
          timeout 20s node ./build/main.js
          exit_code=$?

          # Check the exit code
          if [[ $exit_code -eq 0 ]]; then
            # Command completed successfully or timed out
            exit 0
          else
            # Command encountered an error
            exit 1
          fi
          