name: Lint

on: [push, pull_request]

jobs:
  biome-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v1
      
      - name: Install biome
        run: bun i biome

      - name: Run biome
        run: bun x biome ci .