name: Sync-todos to github-pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - TODO-sync

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      # - name: Install dependencies
      #   run: pip install -r requirements.txt

      - name: Show Folder
        run: |
          cd /home/runner/work/munify/munify && ls -la

      - name: Generate HTML
        run: python todo-sync/todo_sync.py

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1
        with:
          path: todo-sync/public

      - name: Sync-todos
        id: todos
        uses: actions/deploy-pages@v2
