name: Sync-todos to github-pages

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Generate HTML
        run: python todo-sync/main.py

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload HTML
        uses: actions/upload-pages-artifact@v1
        with:
          path: todo-sync/public

      - name: Deploy to GitHub Pages
        id: todos
        uses: actions/deploy-pages@v2
